import 'package:exodus/core/constants/app/app_gap.dart';
import 'package:exodus/presentation/widgets/app_scaffold.dart';
import 'package:flutter/material.dart';

class PrivacyPolicy extends StatelessWidget {
  const PrivacyPolicy({super.key});

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      appBar: AppBar(title: const Text('Privacy Policy')),
      body: ListView(
        physics: const BouncingScrollPhysics(),
        children: [
          const Text(
            'Privacy Policy\nLast updated: June 27, 2025',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
            textAlign: TextAlign.left,
          ),
          Gap.h16,
          const Text(
            'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\n'
            'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Interpretation and Definitions\n\n'
            'Interpretation\n'
            'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\n'
            'Definitions\n'
            'For the purposes of this Privacy Policy:\n\n'
            '• Account means a unique account created for You to access our Service or parts of our Service.\n'
            '• Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n'
            '• Application refers to Exodus, the software program provided by the Company.\n'
            '• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Exodus Trans LLC, 254 Chapman Rd STE 208 #20585 Newark, DE 19702.\n'
            '• For the purpose of the GDPR, the Company is the Data Controller.\n'
            '• Country refers to: Delaware, United States\n'
            '• Data Controller, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.\n'
            '• Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n'
            '• GDPR refers to EU General Data Protection Regulation.\n'
            '• Personal Data is any information that relates to an identified or identifiable individual.\n'
            '• For the purposes of GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity.\n'
            '• Service refers to the Application.\n'
            '• Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.\n'
            '• Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.\n'
            '• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n'
            '• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.\n'
            '• Under GDPR, You can be referred to as the Data Subject or as the User as you are the individual using the Service.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Collecting and Using Your Personal Data\n\n'
            'Types of Data Collected\n\n'
            'Personal Data\n'
            'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n\n'
            '• Email address\n'
            '• First name and last name\n'
            '• Phone number\n'
            '• Usage Data\n\n'
            'Usage Data\n'
            'Usage Data is collected automatically when using the Service.\n\n'
            'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\n'
            'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\n'
            'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Information Collected while Using the Application\n'
            'While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:\n\n'
            '• Information regarding your location\n'
            '• Pictures and other information from your Device\'s camera and photo library\n\n'
            'We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company\'s servers and/or a Service Provider\'s server or it may be simply stored on Your device.\n\n'
            'You can enable or disable access to this information at any time, through Your Device settings.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Use of Your Personal Data\n'
            'The Company may use Personal Data for the following purposes:\n\n'
            '• To provide and maintain our Service, including to monitor the usage of our Service.\n'
            '• To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.\n'
            '• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.\n'
            '• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.\n'
            '• To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.\n'
            '• To manage Your requests: To attend and manage Your requests to Us.\n'
            '• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.\n'
            '• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'We may share Your personal information in the following situations:\n\n'
            '• With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.\n'
            '• For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.\n'
            '• With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.\n'
            '• With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.\n'
            '• With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.\n'
            '• With Your consent: We may disclose Your personal information for any other purpose with Your consent.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Retention of Your Personal Data\n'
            'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\n'
            'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Transfer of Your Personal Data\n'
            'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.\n\n'
            'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.\n\n'
            'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Delete Your Personal Data\n'
            'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.\n\n'
            'Our Service may give You the ability to delete certain information about You from within the Service.\n\n'
            'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.\n\n'
            'Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Disclosure of Your Personal Data\n\n'
            'Business Transactions\n'
            'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.\n\n'
            'Law enforcement\n'
            'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).\n\n'
            'Other legal requirements\n'
            'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:\n\n'
            '• Comply with a legal obligation\n'
            '• Protect and defend the rights or property of the Company\n'
            '• Prevent or investigate possible wrongdoing in connection with the Service\n'
            '• Protect the personal safety of Users of the Service or the public\n'
            '• Protect against legal liability',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Security of Your Personal Data\n'
            'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Detailed Information on the Processing of Your Personal Data\n'
            'The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.\n\n'
            'Analytics\n'
            'We may use third-party Service providers to monitor and analyze the use of our Service.\n\n'
            'Google Analytics\n'
            'Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.\n\n'
            'You may opt-out of certain Google Analytics features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy\n\n'
            'For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Payments\n'
            'We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).\n\n'
            'We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.\n\n'
            'Apple Store In-App Payments\n'
            'Their Privacy Policy can be viewed at https://www.apple.com/legal/privacy/en-ww/\n\n'
            'Google Play In-App Payments\n'
            'Their Privacy Policy can be viewed at https://www.google.com/policies/privacy/',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'GDPR Privacy\n\n'
            'Legal Basis for Processing Personal Data under GDPR\n'
            'We may process Personal Data under the following conditions:\n\n'
            '• Consent: You have given Your consent for processing Personal Data for one or more specific purposes.\n'
            '• Performance of a contract: Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.\n'
            '• Legal obligations: Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.\n'
            '• Vital interests: Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.\n'
            '• Public interests: Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.\n'
            '• Legitimate interests: Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.\n\n'
            'In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Your Rights under the GDPR\n'
            'The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.\n\n'
            'You have the right under this Privacy Policy, and by law if You are within the EU, to:\n\n'
            '• Request access to Your Personal Data. The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.\n'
            '• Request correction of the Personal Data that We hold about You. You have the right to have any incomplete or inaccurate information We hold about You corrected.\n'
            '• Object to processing of Your Personal Data. This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.\n'
            '• Request erasure of Your Personal Data. You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.\n'
            '• Request the transfer of Your Personal Data. We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.\n'
            '• Withdraw Your consent. You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Exercising of Your GDPR Data Protection Rights\n'
            'You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.\n\n'
            'You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Children\'s Privacy\n'
            'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.\n\n'
            'If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent\'s consent before We collect and use that information.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Links to Other Websites\n'
            'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit.\n\n'
            'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Changes to this Privacy Policy\n'
            'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\n'
            'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.\n\n'
            'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
            textAlign: TextAlign.justify,
          ),
          Gap.h16,
          const Text(
            'Contact Us\n'
            'If you have any questions about this Privacy Policy, You can contact us:\n\n'
            '• By email: contactus@exodus-qa.com',
            textAlign: TextAlign.justify,
          ),
        ],
      ),
    );
  }
}
